version: '2.7.12-SNAPSHOT'

services:
  database:
    image: postgres
    restart: always
    container_name: database_1
    ports:
      - 5433:5432
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: k464350g
      POSTGRES_DB: FansDream
    volumes:
      - postgres_volume:/var/lib/postgresql/data
  application:
    image: app
    container_name: application_1
    ports:
      - 8080:8080
    depends_on:
      - database
    environment:
      - "SPRING_DATASOURCE_USERNAME=postgres"
      - "SPRING_DATASOURCE_PASSWORD=k464350g"
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/FansDream"

volumes:
  postgres_volume:
    external: true